# Generated by Django 5.2.3 on 2025-09-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.TextField()),
                ('nome_linha', models.TextField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'status_linha',
                'managed': False,
            },
        ),
    ]
