# Generated by Django 5.2.3 on 2025-09-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParadasLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_linha', models.TextField()),
                ('inicio_parada', models.TextField()),
                ('fim_parada', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paradas_linha',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='StatusLinha',
        ),
    ]
